package com.xx.yuefang.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xx.yuefang.database.entity.City;
import com.xx.yuefang.database.entity.Province;
import com.xx.yuefang.database.entity.SearchStr;
import com.xx.yuefang.database.entity.SystemData;
import com.xx.yuefang.database.entity.UserBean;
import com.xx.yuefang.database.entity.Zone;

import com.xx.yuefang.database.CityDao;
import com.xx.yuefang.database.ProvinceDao;
import com.xx.yuefang.database.SearchStrDao;
import com.xx.yuefang.database.SystemDataDao;
import com.xx.yuefang.database.UserBeanDao;
import com.xx.yuefang.database.ZoneDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoConfig;
    private final DaoConfig provinceDaoConfig;
    private final DaoConfig searchStrDaoConfig;
    private final DaoConfig systemDataDaoConfig;
    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig zoneDaoConfig;

    private final CityDao cityDao;
    private final ProvinceDao provinceDao;
    private final SearchStrDao searchStrDao;
    private final SystemDataDao systemDataDao;
    private final UserBeanDao userBeanDao;
    private final ZoneDao zoneDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        provinceDaoConfig = daoConfigMap.get(ProvinceDao.class).clone();
        provinceDaoConfig.initIdentityScope(type);

        searchStrDaoConfig = daoConfigMap.get(SearchStrDao.class).clone();
        searchStrDaoConfig.initIdentityScope(type);

        systemDataDaoConfig = daoConfigMap.get(SystemDataDao.class).clone();
        systemDataDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        zoneDaoConfig = daoConfigMap.get(ZoneDao.class).clone();
        zoneDaoConfig.initIdentityScope(type);

        cityDao = new CityDao(cityDaoConfig, this);
        provinceDao = new ProvinceDao(provinceDaoConfig, this);
        searchStrDao = new SearchStrDao(searchStrDaoConfig, this);
        systemDataDao = new SystemDataDao(systemDataDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        zoneDao = new ZoneDao(zoneDaoConfig, this);

        registerDao(City.class, cityDao);
        registerDao(Province.class, provinceDao);
        registerDao(SearchStr.class, searchStrDao);
        registerDao(SystemData.class, systemDataDao);
        registerDao(UserBean.class, userBeanDao);
        registerDao(Zone.class, zoneDao);
    }
    
    public void clear() {
        cityDaoConfig.clearIdentityScope();
        provinceDaoConfig.clearIdentityScope();
        searchStrDaoConfig.clearIdentityScope();
        systemDataDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
        zoneDaoConfig.clearIdentityScope();
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public ProvinceDao getProvinceDao() {
        return provinceDao;
    }

    public SearchStrDao getSearchStrDao() {
        return searchStrDao;
    }

    public SystemDataDao getSystemDataDao() {
        return systemDataDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public ZoneDao getZoneDao() {
        return zoneDao;
    }

}
