package com.xx.yuefang.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xx.yuefang.database.entity.SystemData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SYSTEM_DATA".
*/
public class SystemDataDao extends AbstractDao<SystemData, Long> {

    public static final String TABLENAME = "SYSTEM_DATA";

    /**
     * Properties of entity SystemData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property HotKeywords = new Property(1, String.class, "HotKeywords", false, "HOT_KEYWORDS");
        public final static Property UserQuickChat = new Property(2, String.class, "UserQuickChat", false, "USER_QUICK_CHAT");
        public final static Property SalespersonQuickChat = new Property(3, String.class, "SalespersonQuickChat", false, "SALESPERSON_QUICK_CHAT");
    }


    public SystemDataDao(DaoConfig config) {
        super(config);
    }
    
    public SystemDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SYSTEM_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"HOT_KEYWORDS\" TEXT," + // 1: HotKeywords
                "\"USER_QUICK_CHAT\" TEXT," + // 2: UserQuickChat
                "\"SALESPERSON_QUICK_CHAT\" TEXT);"); // 3: SalespersonQuickChat
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SYSTEM_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SystemData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String HotKeywords = entity.getHotKeywords();
        if (HotKeywords != null) {
            stmt.bindString(2, HotKeywords);
        }
 
        String UserQuickChat = entity.getUserQuickChat();
        if (UserQuickChat != null) {
            stmt.bindString(3, UserQuickChat);
        }
 
        String SalespersonQuickChat = entity.getSalespersonQuickChat();
        if (SalespersonQuickChat != null) {
            stmt.bindString(4, SalespersonQuickChat);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SystemData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String HotKeywords = entity.getHotKeywords();
        if (HotKeywords != null) {
            stmt.bindString(2, HotKeywords);
        }
 
        String UserQuickChat = entity.getUserQuickChat();
        if (UserQuickChat != null) {
            stmt.bindString(3, UserQuickChat);
        }
 
        String SalespersonQuickChat = entity.getSalespersonQuickChat();
        if (SalespersonQuickChat != null) {
            stmt.bindString(4, SalespersonQuickChat);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SystemData readEntity(Cursor cursor, int offset) {
        SystemData entity = new SystemData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // HotKeywords
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // UserQuickChat
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // SalespersonQuickChat
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SystemData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHotKeywords(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserQuickChat(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSalespersonQuickChat(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SystemData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SystemData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SystemData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
